# Generated by Django 4.2.7 on 2023-12-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_plate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
